name: Release
on: [push]

jobs:
  release-image:
    runs-on: imgbuilder
    env:
      CONTAINER_REGISTRY: gitea.konchin.com
      GITEA_TAG: latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up rootca
        run: |
          echo "${{ vars.ROOTCA }}" | tee rootca.pem          

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v3
        with:
          config-inline: |
            debug = true
            [registry."${{ env.CONTAINER_REGISTRY }}"]
              ca = ["rootca.pem"]                        

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ env.CONTAINER_REGISTRY }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      - name: Setup env
        run: |
          echo "GITEA_REPO=${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV
          echo "GITEA_REF_NAME=${GITHUB_REF_NAME}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV                    

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: |
            linux/amd64                        
          push: true
          tags: |
            ${{ env.CONTAINER_REGISTRY }}/${{ env.GITEA_REPO }}:${{ env.GITEA_REF_NAME }}
            ${{ env.CONTAINER_REGISTRY }}/${{ env.GITEA_REPO }}:${{ env.GITEA_TAG }}                        

